# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import rvpsite.contact.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phone', models.CharField(max_length=11, validators=[rvpsite.contact.validators.validate_phone], verbose_name='telefone')),
                ('msg', models.TextField(max_length=700, verbose_name='mensagem')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ('-created_at',),
            },
        ),
    ]
