# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',), 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='enviada em'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ipaddr',
            field=models.GenericIPAddressField(verbose_name='endereço IP'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(max_length=700, verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='telefone'),
        ),
    ]
