# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import rvpsite.contact.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ipaddr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, validators=[rvpsite.contact.validators.validate_phone], verbose_name='telefone'),
        ),
    ]